### ISSUE TITLE
result app not working 

### ISSUE THREAD

**Issue by gurpreet84** [mmumshad/kubernetes-example-voting-app#5]
result app not working - its not updating the result, how can we troubleshoot

**Comment by leaderdevops** [comment]
doesn't work for me as well.. were you able to fix it Gurpreet?

**Comment by leaderdevops** [comment]
@mmumshad pls look into this.

**Comment by bipul34** [comment]
@mmumshad /All , I guess there is an issue on the parent repository (dockersamples/example-voting-app) after a latest commit 

Below are the references 
https://github.com/dockersamples/example-voting-app/issues/165
https://github.com/dockersamples/example-voting-app/commit/245c8f3aa1291e3e1f1cbbe519b672045456b2a9#commitcomment-37881943

Can somebody please confirm ..

Thanks
Bipul

**Comment by btrx-rkazi** [comment]
Is the result app working? i see it gives same 50% 50% result for any selection

**Comment by rob2k40** [comment]
It's not working for me as well.
@mmumshad Could you please help out?

**Comment by pingtotgp** [comment]
Please try adding the below env variable in the postgres-pod.yaml file

```
  - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
```

it works.

**Comment by rob2k40** [comment]
@mmumshad Still not working. It shows result as 50-50 only even after voting
